# Generated by Django 3.1.1 on 2020-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_line', models.CharField(max_length=1000)),
                ('most_frequency_character', models.CharField(max_length=100)),
                ('line_index', models.CharField(max_length=100)),
            ],
        ),
    ]
