# Generated by Django 3.1.1 on 2020-09-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='line_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='most_frequency_character',
            field=models.CharField(max_length=1),
        ),
    ]
