# Generated by Django 3.1.1 on 2020-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200925_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text_line',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
