# Generated by Django 3.1.1 on 2020-11-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200925_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmodel',
            name='line_index',
        ),
    ]
